### ISSUE TITLE
Scripts whitespace removed in new serverless versions

### ISSUE THREAD

**Issue by Limess** [mvila/serverless-plugin-scripts#5] opened 2018-06-14 10:36 UTC
Since serverless `1.27.0`, the scripts ran by this plugin have all whitespace removed.

i.e.
```yaml
  deploy:
      finalise: >
          cp -rf public/favicon.ico dist &&
          aws s3 sync dist s3://some-url
```

runs 

```shell
cp-rfpublic/favicon.icodist&&awss3syncdists3://some-url
```

**Comment by mvila** [comment] 2018-06-17 00:19
Hi @Limess,

I am sorry but I couldn't reproduce your issue with Serverless 1.27.3. Also, I double-checked my code, and I couldn't find anything that could remove the whitespace. I just take the command strings (as parsed by Serverless) and execute them with `execSync`. So I guess the root of the problem might be somewhere else.

**Comment by Limess** [comment] 2018-06-25 21:45
Thanks @mvila. Agreed that it doesn't seem related to this plugin - but it's definitely impacted our usage of it across a few projects.

I haven't had time to dig into what is causing this in the main serverless library, will try to if I have the chance. 

For reference, the above example is a slight simplification. We're currently using a yaml anchor to share the above command, i.e.:

```yaml
  custom:
    deployScript: &deploy_script >
      cp -rf public/favicon.ico dist &&
      aws s3 sync dist s3://some-url
    
...

  deploy:
      finalise: *deploy_script
```

which worked in the older serverless versions.

**Comment by mvila** [comment] 2018-06-28 01:10
Okay, @Limess, I close this issue, but please let me know if you can find an explanation.

**Closed as completed by mvila** 2018-06-28 01:10 UTC
